In [5]:
import numpy as np

In [6]:
def generate_columns_map():
    position_map = [2 ** i for i in range(49)]

    columns_map = []
    for column_number in range(7):
        column_values = position_map[7 * column_number: 7 * column_number + 6]
        columns_map.append(column_values)

    return columns_map

In [40]:
def bitboard_from_integer(integer):
    bit_board = []
    columns_map = generate_columns_map()
    for column in columns_map:
        column_cells = []
        for element in column:
            cell_status = (element & integer) > 0
            column_cells.append(cell_status)
        bit_board.append(column_cells)
    return np.flipud(np.array(bit_board).transpose()).astype(int)

In [41]:
def game_layout_from_mask_and_player(bit_board, mask):
    return bitboard_from_integer(bit_board) +  bitboard_from_integer(mask)

In [44]:
bit_board =  4443259030528
mask = 4518169337729

In [45]:
game_layout_from_mask_and_player(bit_board, mask)

array([[0, 1, 0, 2, 2, 0, 0],
       [0, 2, 0, 2, 1, 0, 0],
       [0, 2, 0, 1, 2, 0, 0],
       [0, 1, 0, 2, 1, 0, 0],
       [0, 1, 1, 2, 1, 1, 0],
       [1, 1, 2, 2, 1, 2, 2]])

In [56]:
np.argsort([len(column) for column in generate_columns_map()])

array([0, 1, 2, 3, 4, 5, 6], dtype=int32)

In [46]:
bit_board = 74910307201
mask = 120122826625

In [47]:
game_layout_from_mask_and_player(bit_board, mask)

array([[0, 2, 0, 1, 1, 0, 0],
       [0, 1, 0, 1, 2, 0, 0],
       [0, 1, 0, 2, 1, 0, 0],
       [0, 2, 0, 1, 2, 0, 0],
       [0, 2, 2, 1, 2, 2, 0],
       [2, 2, 1, 1, 2, 1, 0]])

In [83]:
plays = [0, 1, 2, 3, 4, 5, 6]
for i in reversed(range(7)):
    pop_index = i//2
    pop_element = plays.pop(i)
    print(pop_index, pop_element)
    

#plays = [plays.pop(i//2) for i in reversed(range(1, l+1))

3 6
2 5
2 4
1 3
1 2
0 1
0 0


In [90]:
for r in reversed(range(1, 8)):
    i_plays = list(range(r))
    plays = i_plays[:]
    print(plays)
    r_plays = [plays.pop(i//2) for i in reversed(range(len(plays)))]
    print(i_plays, '->', r_plays)

[0, 1, 2, 3, 4, 5, 6]
[0, 1, 2, 3, 4, 5, 6] -> [3, 2, 4, 1, 5, 0, 6]
[0, 1, 2, 3, 4, 5]
[0, 1, 2, 3, 4, 5] -> [2, 3, 1, 4, 0, 5]
[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4] -> [2, 1, 3, 0, 4]
[0, 1, 2, 3]
[0, 1, 2, 3] -> [1, 2, 0, 3]
[0, 1, 2]
[0, 1, 2] -> [1, 0, 2]
[0, 1]
[0, 1] -> [0, 1]
[0]
[0] -> [0]


In [77]:
plays = [plays.pop(i//2) for i in reversed(range(l))]

In [78]:
plays

[2, 3, 1, 4, 0, 5]